start = expr+

expr = atom / quote / list

list = _ '(' _ first:expr rest:spaceExpr* _ ')' _ {
  return [first].concat(rest);
}

spaceExpr = ws+ e:expr {
  return e;
}

quote = _ "'" e:expr _ {
  return ['quote', e];
}

atom = chars:validChar+ {
  return chars.join('');
}

validChar = [0-9a-zA-Z_?!+\-=@#$%^&*/.]

ws = [ \t\n]

_ = (ws / comment)*

comment = ';;' text:[^\n]* '\n' {
  return text.join('');
}
